import { describe, it, expect } from 'vitest'
import { AbstractDTOEntity } from '../AbstractDTOEntity'
import type { Constructor } from '../../decorators/Field'
import {
  AutoGeneratedField,
  ExcludeField,
  Field,
  dtoMetadata,
  ParseError,
} from '../../decorators/Field'

describe('Field decorator registry and AbstractDTOEntity', () => {
  it('registers metadata and parses valid input with transform', () => {
    class Person extends AbstractDTOEntity {
      @Field({
        validators: [(v) => (typeof v === 'string' && v.length > 0 ? null : 'must not be empty')],
      })
      name!: string

      @Field({ transform: (v) => new Date(v as string) })
      birth!: Date
    }

    const instance = new Person()
    const meta = dtoMetadata.get(Person as unknown as Constructor)
    expect(meta).toBeDefined()
    expect(meta!.has('name')).toBe(true)
    expect(meta!.has('birth')).toBe(true)

    const raw = { name: 'Ana', birth: '2000-01-01' }
    const p = Person.parse(raw)

    expect(p).toBeInstanceOf(Person)
    expect(p.name).toBe('Ana')
    expect(p.birth).toBeInstanceOf(Date)
    expect(isNaN((p.birth as Date).getTime())).toBe(false)
  })

  it('throws ParseError with issues on invalid transform and validation', () => {
    class Event extends AbstractDTOEntity {
      @Field({ validators: [(v) => (typeof v === 'string' && v.length > 0 ? null : 'required')] })
      title!: string

      @Field({
        transform: (v) => {
          const d = new Date(v as string)
          if (isNaN(d.getTime())) throw new Error('invalid date')
          return d
        },
      })
      date!: Date
    }

    const bad = { title: '', date: 'not-a-date' }

    expect(() => Event.parse(bad)).toThrow(ParseError)

    let err: ParseError | undefined
    try {
      Event.parse(bad)
    } catch (e) {
      err = e as ParseError
    }

    expect(err).toBeDefined()
    expect(err?.issues).toBeDefined()
    expect(Object.keys(err?.issues ?? {}).length).toBeGreaterThanOrEqual(1)
    expect(err?.issues).toHaveProperty('title')
    expect(err?.issues).toHaveProperty('date')
  })

  it('serializes and creates clean payloads using helpers', () => {
    class JobDto extends AbstractDTOEntity {
      @Field() id?: number

      @Field() title: string = 'Developer'

      @AutoGeneratedField()
      @Field()
      generated!: string

      @ExcludeField()
      @Field()
      secret!: string
    }

    const job = JobDto.parse({ title: 'Developer', generated: 'x', secret: 's' })
    const json = job.toJSON()
    const createPayload = job.toCreatePayload()

    expect(json).toEqual(expect.objectContaining({ title: 'Developer' }))
    expect(json).not.toHaveProperty('secret')
    expect(createPayload).toEqual(expect.objectContaining({ title: 'Developer' }))
    expect(createPayload).not.toHaveProperty('generated')
    expect(createPayload).not.toHaveProperty('secret')
  })
})
