// ============================================================================
// field-annotations.ts — sistem de decoratori pentru DTO-uri, bazat pe Stage 3
// ============================================================================
//
// Scop:
//   - fiecare decorator adauga o instanta a unei clase de anotare la un camp;
//   - metadata-ul este stocat intr-un registru orientat pe obiecte, fara a
//     modifica constructorul sau prototype-ul in mod vizibil;
//   - logica de validare, transformare si serializare este delegata catre
//     obiecte specializate, astfel incat OOP sa faca munca grea.
// ============================================================================

interface ValidationContext {
  key: string
  target: unknown
}

interface ValidationResult {
  valid: boolean
  message?: string
}

type ValidatorResult = ValidationResult | boolean | string | null | undefined
type ValidatorFn<T = unknown> = (value: T, ctx: ValidationContext) => ValidatorResult
type TransformFn<TIn = unknown, TOut = unknown> = (value: TIn, target: unknown) => TOut

type Constructor<T = object> = new (...args: unknown[]) => T
type AnnotationConstructor<T extends Annotation = Annotation> = abstract new (...args: never[]) => T

type FieldDecorator = (value: unknown, context: ClassFieldDecoratorContext) => void

type ClassCtor = new (...args: unknown[]) => object

/**
 * Clasa de baza pentru toate anotatiile de camp.
 * Fiecare subclasa pastreaza datele specifice si isi poate implementa logica
 * proprie de validare sau transformare.
 */
abstract class Annotation {
  /** Nume human-readable, implicit numele clasei concrete. */
  get name(): string {
    return this.constructor.name
  }
}

/**
 * Anotare structurala simpla care marcheaza un camp ca parte a modelului.
 * Este folosita pentru a asigura ca un camp decorat cu @Field() apare in
 * metadata chiar daca nu are transformari sau validatori.
 */
class FieldDefinition extends Annotation {}

/**
 * Marcheaza un camp care trebuie eliminat din payload-ul de iesire.
 */
class Exclude extends Annotation {}

/**
 * Marcheaza un camp generat de motorul bazei de date sau de sistem.
 */
class AutoGenerated extends Annotation {}

/**
 * Inveleste un validator arbitrar.
 */
class Validator extends Annotation {
  constructor(public readonly fn: ValidatorFn<unknown>) {
    super()
  }
}

/**
 * Inveleste o transformare aplicata la serializare sau creare payload.
 */
class Transform extends Annotation {
  constructor(public readonly fn: TransformFn<unknown, unknown>) {
    super()
  }
}

/**
 * Clasa de baza pentru anotatiile de constrangere.
 * O constrangere cunoaste propria logica de validare si poate oferi un mesaj
 * implicit personalizat.
 */
abstract class ConstraintAnnotation extends Annotation {
  protected message?: string

  abstract check(value: unknown, ctx: ValidationContext): boolean
  abstract defaultMessage(ctx: ValidationContext): string

  validate(value: unknown, ctx: ValidationContext): ValidationResult {
    if (this.check(value, ctx)) {
      return { valid: true }
    }

    return {
      valid: false,
      message: this.message ?? this.defaultMessage(ctx),
    }
  }

  withMessage(message: string): this {
    this.message = message
    return this
  }
}

/**
 * Constrangere pentru lungime sau dimensiune.
 */
class SizeConstraint extends ConstraintAnnotation {
  constructor(private readonly options: { min?: number; max?: number }) {
    super()
  }

  check(value: unknown): boolean {
    const length =
      typeof value === 'string' || Array.isArray(value)
        ? value.length
        : value == null
          ? 0
          : undefined

    if (length === undefined) {
      return false
    }

    const { min, max } = this.options
    if (min !== undefined && length < min) {
      return false
    }
    if (max !== undefined && length > max) {
      return false
    }

    return true
  }

  defaultMessage(ctx: ValidationContext): string {
    return `${ctx.key} must have length between ${this.options.min ?? 0} and ${this.options.max ?? '∞'}`
  }
}

/**
 * Constrangere pentru date, cu limite optionale before/after.
 */
class DateTimeConstraint extends ConstraintAnnotation {
  constructor(private readonly options: { before?: Date; after?: Date }) {
    super()
  }

  check(value: unknown): boolean {
    const date = value instanceof Date ? value : new Date(value as string)
    if (Number.isNaN(date.getTime())) {
      return false
    }

    const { before, after } = this.options
    if (before && date >= before) {
      return false
    }
    if (after && date <= after) {
      return false
    }

    return true
  }

  defaultMessage(ctx: ValidationContext): string {
    return `${ctx.key} must be a valid date within the configured range`
  }
}

/**
 * Constrangere pentru valori numerice in interval.
 */
class RangeConstraint extends ConstraintAnnotation {
  constructor(private readonly options: { min?: number; max?: number }) {
    super()
  }

  check(value: unknown): boolean {
    if (typeof value !== 'number' || Number.isNaN(value)) {
      return false
    }

    const { min, max } = this.options
    if (min !== undefined && value < min) {
      return false
    }
    if (max !== undefined && value > max) {
      return false
    }

    return true
  }

  defaultMessage(ctx: ValidationContext): string {
    return `${ctx.key} must be between ${this.options.min ?? '-∞'} and ${this.options.max ?? '∞'}`
  }
}

/**
 * Constrangere bazata pe expresie regulata.
 */
class PatternConstraint extends ConstraintAnnotation {
  constructor(private readonly regex: RegExp) {
    super()
  }

  check(value: unknown): boolean {
    return typeof value === 'string' && this.regex.test(value)
  }

  defaultMessage(ctx: ValidationContext): string {
    return `${ctx.key} does not match required pattern ${this.regex}`
  }
}

/**
 * Constrangere pentru o lista finita de valori permise.
 */
class EnumConstraint extends ConstraintAnnotation {
  constructor(private readonly values: readonly unknown[]) {
    super()
  }

  check(value: unknown): boolean {
    return this.values.includes(value)
  }

  defaultMessage(ctx: ValidationContext): string {
    return `${ctx.key} must be one of [${this.values.join(', ')}]`
  }
}

/**
 * Colectie de anotari pentru un singur camp.
 * Unicitatea este asigurata pe clasa concreta a anotarii, similar cu Java.
 */
class FieldAnnotations {
  private readonly byClass = new Map<AnnotationConstructor, Annotation>()

  constructor(
    public readonly key: string,
    annotations: Iterable<Annotation> = [],
  ) {
    for (const annotation of annotations) {
      this.add(annotation)
    }
  }

  add(annotation: Annotation): this {
    this.byClass.set(annotation.constructor as AnnotationConstructor, annotation)
    return this
  }

  has(type: AnnotationConstructor): boolean {
    return this.byClass.has(type)
  }

  get<T extends Annotation>(type: AnnotationConstructor): T | undefined {
    return this.byClass.get(type) as T | undefined
  }

  toArray(): Annotation[] {
    return Array.from(this.byClass.values())
  }

  toSet(): Set<Annotation> {
    return new Set(this.byClass.values())
  }

  clone(): FieldAnnotations {
    return new FieldAnnotations(this.key, this.toArray())
  }

  [Symbol.iterator](): IterableIterator<Annotation> {
    return this.byClass.values()
  }
}

/**
 * Sursa abstracta de metadata pentru campuri. Consumatorii (validator,
 * transformer, serializer, payload builder) depind de aceasta abstractie
 * in loc de implementarea concreta a registrului (Dependency Inversion).
 */
interface FieldMetadataSource {
  getFor(ctor: ClassCtor): FieldAnnotations[]
}

/**
 * Registru de metadata pentru campuri.
 * Se bazeaza pe un WeakMap de la constructor la harta de campuri.
 */
class FieldMetadataRegistry implements FieldMetadataSource {
  private readonly registry = new WeakMap<ClassCtor, Map<string, FieldAnnotations>>()

  private getParentCtor(target: ClassCtor): ClassCtor | undefined {
    const parent = Object.getPrototypeOf(target) as ClassCtor | null
    return parent && parent !== Function.prototype ? parent : undefined
  }

  private getOrCreateFieldMap(target: ClassCtor): Map<string, FieldAnnotations> {
    const existing = this.registry.get(target)
    if (existing) {
      return existing
    }

    const parent = this.getParentCtor(target)
    const inherited = parent ? this.getOrCreateFieldMap(parent) : undefined
    const next = new Map<string, FieldAnnotations>(
      inherited ? Array.from(inherited.entries(), ([key, value]) => [key, value.clone()]) : [],
    )

    this.registry.set(target, next)
    return next
  }

  register(instance: object, key: string, annotation: Annotation): void {
    const ctor = instance.constructor as ClassCtor
    const fieldMap = this.getOrCreateFieldMap(ctor)
    const fieldAnnotations = fieldMap.get(key) ?? new FieldAnnotations(key)
    fieldAnnotations.add(annotation)
    fieldMap.set(key, fieldAnnotations)
  }

  getFor(ctor: ClassCtor): FieldAnnotations[] {
    return Array.from(this.getOrCreateFieldMap(ctor).values())
  }

  getForProperty(ctor: ClassCtor, key: string): FieldAnnotations | undefined {
    return this.getOrCreateFieldMap(ctor).get(key)
  }

  getFieldMap(ctor: ClassCtor): Map<string, FieldAnnotations> {
    return this.getOrCreateFieldMap(ctor)
  }
}

const registry = new FieldMetadataRegistry()

class MetadataView {
  constructor(private readonly values: Map<string, FieldAnnotations>) {}

  has(key: string): boolean {
    return this.values.has(key)
  }

  get(key: string): FieldAnnotations | undefined {
    return this.values.get(key)
  }
}

/**
 * Registru public pentru utilizare in teste sau in aplicatii externe.
 */
const dtoMetadata = {
  get(target: Constructor): MetadataView | undefined {
    return new MetadataView(registry.getFieldMap(target as ClassCtor))
  },
}

/**
 * Construiește un decorator de camp bazat pe Stage 3.
 * Metadata este inregistrata la initializarea instanței prin context.addInitializer.
 * Accepta fie o singura anotare, fie o lista, astfel incat decoratorii simpli
 * (ExcludeField, Size, ...) si cei compusi (Field) folosesc aceeasi cablare,
 * fara logica duplicata.
 */
function createFieldDecorator(
  annotationFactory: () => Annotation | readonly Annotation[],
): FieldDecorator {
  return (_value: unknown, context: ClassFieldDecoratorContext) => {
    if (context.kind !== 'field') {
      return
    }

    const propertyKey = String(context.name)
    const produced = annotationFactory()
    const annotations = Array.isArray(produced) ? produced : [produced]

    for (const annotation of annotations) {
      registry.register(context. as object, propertyKey, annotation)
    }
  }
}

/**
 * Decorator pentru campuri marcate ca excluse.
 */
function ExcludeField(): FieldDecorator {
  return createFieldDecorator(() => new Exclude())
}

/**
 * Decorator pentru campuri generate automat.
 */
function AutoGeneratedField(): FieldDecorator {
  return createFieldDecorator(() => new AutoGenerated())
}

/**
 * Decorator pentru validatori inline.
 */
function ValidatorField<T = unknown>(fn: ValidatorFn<T>): FieldDecorator {
  return createFieldDecorator(() => new Validator(fn as ValidatorFn<unknown>))
}

/**
 * Decorator pentru transformari inline.
 */
function TransformField<TIn = unknown, TOut = unknown>(fn: TransformFn<TIn, TOut>): FieldDecorator {
  return createFieldDecorator(() => new Transform(fn as TransformFn<unknown, unknown>))
}

/**
 * Decorator pentru constrangere de marime.
 */
function Size(options: { min?: number; max?: number }): FieldDecorator {
  return createFieldDecorator(() => new SizeConstraint(options))
}

/**
 * Decorator pentru constrangere de data.
 */
function DateTime(options: { before?: Date; after?: Date }): FieldDecorator {
  return createFieldDecorator(() => new DateTimeConstraint(options))
}

/**
 * Decorator pentru constrangere de interval numeric.
 */
function Range(options: { min?: number; max?: number }): FieldDecorator {
  return createFieldDecorator(() => new RangeConstraint(options))
}

/**
 * Decorator pentru constrangere bazata pe regex.
 */
function Pattern(regex: RegExp): FieldDecorator {
  return createFieldDecorator(() => new PatternConstraint(regex))
}

/**
 * Decorator pentru o lista finita de valori permise.
 */
function OneOf(values: readonly unknown[]): FieldDecorator {
  return createFieldDecorator(() => new EnumConstraint(values))
}

/**
 * Decorator ergonomic pentru campuri cu transformari si/sau validatori inline.
 */
function Field(
  options: {
    transform?: TransformFn<unknown, unknown>
    validators?: ValidatorFn<unknown>[]
  } = {},
): FieldDecorator {
  return createFieldDecorator(() => {
    const annotations: Annotation[] = [new FieldDefinition()]

    if (options.transform) {
      annotations.push(new Transform(options.transform))
    }

    if (options.validators) {
      for (const validatorFn of options.validators) {
        annotations.push(new Validator(validatorFn))
      }
    }

    return annotations
  })
}

/**
 * Eroare aruncata de AbstractDTOEntity.parse() atunci cand validarea esueaza.
 */
class ParseError extends Error {
  constructor(public readonly issues: Record<string, string>) {
    super('DTO validation failed')
  }
}

/**
 * Ruleaza validatoarele si constrangerile asociate unei instante DTO.
 * Singura responsabilitate: transforma metadata de camp in erori de validare.
 * Depinde de FieldMetadataSource (nu de FieldMetadataRegistry direct), asa
 * ca poate fi testata cu o sursa de metadata falsa.
 *
 *  * Elimina campurile marcate @Exclude atunci cand o instanta este serializata.
 * Singura responsabilitate: produce reprezentarea publica a instantei.
 *
 * Aplica transformarile de camp declarate prin @Transform / @Field({ transform }).
 * Singura responsabilitate: produce o copie transformata a instantei.
 *
 * Ruleaza validatoarele si constrangerile asociate unei instante DTO.
 * Singura responsabilitate: transforma metadata de camp in erori de validare.
 * Depinde de FieldMetadataSource (nu de FieldMetadataRegistry direct), asa
 * ca poate fi testata cu o sursa de metadata falsa.
 *
 * Aplica transformarile de camp declarate prin @Transform / @Field({ transform }).
 * Singura responsabilitate: produce o copie transformata a instantei.
 */
class DtoTransformer {
  constructor(private readonly metadata: FieldMetadataSource = registry) {}

  validate(instance: object): true {
    const ctor = instance.constructor as ClassCtor
    const issues: Record<string, string> = {}

    for (const fieldAnnotations of this.metadata.getFor(ctor)) {
      if (fieldAnnotations.has(AutoGenerated)) {
        //TODO continue
      }

      const value = (instance as Record<string, unknown>)[fieldAnnotations.key]
      const ctx: ValidationContext = { key: fieldAnnotations.key, target: instance }

      for (const annotation of fieldAnnotations.toArray()) {
        this.collectIssue(annotation, value, ctx, issues)
      }
    }

    if (Object.keys(issues).length > 0) {
      throw new ParseError(issues)
    }

    return true
  }

  private collectIssue(
    annotation: Annotation,
    value: unknown,
    ctx: ValidationContext,
    issues: Record<string, string>,
  ): void {
    if (annotation instanceof Validator) {
      const normalized = this.normalize(annotation.fn(value, ctx), ctx)
      if (!normalized.valid) {
        issues[ctx.key] = normalized.message ?? `${ctx.key} is invalid`
      }
      return
    }

    if (annotation instanceof ConstraintAnnotation) {
      const result = annotation.validate(value, ctx)
      if (!result.valid) {
        issues[ctx.key] = result.message ?? `${ctx.key} is invalid`
      }
    }
  }

  private normalize(result: ValidatorResult, ctx: ValidationContext): ValidationResult {
    if (result == null) {
      return { valid: true }
    }

    if (typeof result === 'boolean') {
      return {
        valid: result,
        message: result ? undefined : `${ctx.key} failed validation`,
      }
    }

    if (typeof result === 'string') {
      return {
        valid: false,
        message: result,
      }
    }

    return result
  }
  transform(instance: object): Record<string, unknown> {
    const ctor = instance.constructor as ClassCtor
    const out: Record<string, unknown> = { ...(instance as Record<string, unknown>) }

    for (const fieldAnnotations of this.metadata.getFor(ctor)) {
      const transformAnnotation = fieldAnnotations.get(Transform) as Transform | undefined
      if (transformAnnotation) {
        out[fieldAnnotations.key] = transformAnnotation.fn(out[fieldAnnotations.key], instance)
      }
    }

    return out
  }
  serialize(instance: object): Record<string, unknown> {
    const ctor = instance.constructor as ClassCtor
    const excludedKeys = new Set(
      this.metadata
        .getFor(ctor)
        .filter((field) => field.has(Exclude))
        .map((field) => field.key),
    )

    const out: Record<string, unknown> = {}
    for (const [key, value] of Object.entries(instance)) {
      if (!excludedKeys.has(key)) {
        out[key] = value
      }
    }

    return out
  }

  build(instance: object): Record<string, unknown> {
    const ctor = instance.constructor as ClassCtor
    const fields = this.metadata.getFor(ctor)
    const skippedKeys = new Set(
      fields
        .filter((field) => field.has(Exclude) || field.has(AutoGenerated))
        .map((field) => field.key),
    )
    const transformsByKey = new Map(
      fields
        .filter((field) => field.has(Transform))
        .map((field) => [field.key, (field.get(Transform) as Transform).fn]),
    )

    const out: Record<string, unknown> = {}
    for (const [key, value] of Object.entries(instance)) {
      if (skippedKeys.has(key)) {
        continue
      }

      out[key] = transformsByKey.has(key) ? transformsByKey.get(key)!(value, instance) : value
    }

    return out
  }
}

const dtoTransformer = new DtoTransformer()

export {
  // Tipuri
  type ValidationContext,
  type ValidationResult,
  type ValidatorResult,
  type ValidatorFn,
  type TransformFn,
  type Constructor,
  type AnnotationConstructor,
  // Clase annotation
  Annotation,
  FieldDefinition,
  Exclude,
  AutoGenerated,
  Validator,
  Transform,
  ConstraintAnnotation,
  SizeConstraint,
  DateTimeConstraint,
  RangeConstraint,
  PatternConstraint,
  EnumConstraint,
  FieldAnnotations,
  // Public API
  dtoMetadata,
  // Decorators
  ExcludeField,
  AutoGeneratedField,
  ValidatorField,
  TransformField,
  Size,
  DateTime,
  Range,
  Pattern,
  OneOf,
  Field,
  // Metadata readers
  getFieldAnnotations,
  getFieldAnnotationsFor,
  // Error class
  ParseError,
  // Exportat pentru alte module, dar nu pentru consumatori finali
  createFieldDecorator,
  dtoTransformer,
}
