// ============================================================================
// field-annotations.ts — sistem de decoratori pentru DTO-uri, bazat pe Stage 3
// ============================================================================
//
// Scop:
//   - fiecare decorator adauga o instanta a unei clase de anotare la un camp;
//   - metadata-ul este stocat intr-un registru orientat pe obiecte, fara a
//     modifica constructorul sau prototype-ul in mod vizibil;
//   - logica de validare, transformare si serializare este delegata catre
//     obiecte specializate, astfel incat OOP sa faca munca grea.
// ============================================================================

interface ValidationContext {
  key: string
  target: unknown
}

interface ValidationResult {
  valid: boolean
  message?: string
}

type ValidatorResult = ValidationResult | boolean | string | null | undefined
type ValidatorFn<T = unknown> = (value: T, ctx: ValidationContext) => ValidatorResult
type TransformFn<TIn = unknown, TOut = unknown> = (value: TIn, target: unknown) => TOut

type Constructor<T = object> = new (...args: unknown[]) => T
type AnnotationConstructor<T extends Annotation = Annotation> = abstract new (
  ...args: TransformFn<unknown, unknown>[]
) => T

type DtoFieldDecorator = (value: undefined, context: ClassFieldDecoratorContext) => void

type ClassCtor = new (...args: unknown[]) => object

type DecoratorMetadataObject = Record<PropertyKey, unknown>
const DTO_FIELD_ANNOTATIONS = Symbol('dto.fieldAnnotations')

function getMetadataSymbol(): symbol {
  return typeof Symbol.metadata === 'symbol' ? Symbol.metadata : Symbol.for('Symbol.metadata')
}

function cloneFieldMap(source: Map<string, FieldAnnotations>): Map<string, FieldAnnotations> {
  return new Map(Array.from(source.entries(), ([key, value]) => [key, value.clone()]))
}

function getClassMetadata(ctor: ClassCtor): DecoratorMetadataObject | undefined {
  const current = Reflect.get(ctor, getMetadataSymbol())
  if (current) {
    return current as DecoratorMetadataObject
  }

  // Some implementations may write to the fallback symbol directly.
  const fallback = Reflect.get(ctor, Symbol.for('Symbol.metadata'))
  return fallback as DecoratorMetadataObject | undefined
}

/** Returnează metadata internă asociată unei clase (fără a o crea). */

function getFieldMapFromMetadata(
  metadata: DecoratorMetadataObject | undefined,
): Map<string, FieldAnnotations> | undefined {
  return metadata?.[DTO_FIELD_ANNOTATIONS] as Map<string, FieldAnnotations> | undefined
}

/** Extrage harta de câmpuri din metadata clasei, dacă există. */

function getOwnOrCreateFieldMap(metadata: DecoratorMetadataObject): Map<string, FieldAnnotations> {
  const hasOwnFieldMap = Object.prototype.hasOwnProperty.call(metadata, DTO_FIELD_ANNOTATIONS)

  if (!hasOwnFieldMap) {
    const inherited = metadata[DTO_FIELD_ANNOTATIONS] as Map<string, FieldAnnotations> | undefined
    Object.defineProperty(metadata, DTO_FIELD_ANNOTATIONS, {
      value: inherited ? cloneFieldMap(inherited) : new Map<string, FieldAnnotations>(),
      writable: true,
      configurable: true,
    })
  }

  return metadata[DTO_FIELD_ANNOTATIONS] as Map<string, FieldAnnotations>
}

/** Returnează sau inițializează harta de anotări pentru o clasă. */

/**
 * Clasa de baza pentru toate anotatiile de camp.
 * Fiecare subclasa pastreaza datele specifice si isi poate implementa logica
 * proprie de validare sau transformare.
 */
abstract class Annotation {
  /** Nume human-readable, implicit numele clasei concrete. */
  get name(): string {
    return this.constructor.name
  }
}

/**
 * Anotare structurala simpla care marcheaza un camp ca parte a modelului.
 * Este folosita pentru a asigura ca un camp decorat cu @Field() apare in
 * metadata chiar daca nu are transformari sau validatori.
 */
class FieldDefinition extends Annotation {}

/**
 * Marcheaza un camp care trebuie eliminat din payload-ul de iesire.
 */
class ExcludeAnnotation extends Annotation {}

/**
 * Marcheaza un camp generat de motorul bazei de date sau de sistem.
 */
class AutoGenerated extends Annotation {}

/**
 * Inveleste un validator arbitrar.
 */
class Validator extends Annotation {
  constructor(public readonly fn: ValidatorFn<unknown>) {
    super()
  }
}

/**
 * Inveleste o transformare aplicata la serializare sau creare payload.
 */
class Transform extends Annotation {
  constructor(public readonly fn: TransformFn<unknown, unknown>) {
    super()
  }
}

/**
 * Clasa de baza pentru anotatiile de constrangere.
 * O constrangere cunoaste propria logica de validare si poate oferi un mesaj
 * implicit personalizat.
 */
abstract class ConstraintAnnotation extends Annotation {
  protected message?: string

  abstract check(value: unknown, ctx: ValidationContext): boolean
  abstract defaultMessage(ctx: ValidationContext): string

  validate(value: unknown, ctx: ValidationContext): ValidationResult {
    if (this.check(value, ctx)) {
      return { valid: true }
    }

    return {
      valid: false,
      message: this.message ?? this.defaultMessage(ctx),
    }
  }

  withMessage(message: string): this {
    this.message = message
    return this
  }
}

/**
 * Constrangere pentru lungime sau dimensiune.
 */
class SizeConstraint extends ConstraintAnnotation {
  constructor(private readonly options: { min?: number; max?: number }) {
    super()
  }

  check(value: unknown): boolean {
    const length =
      typeof value === 'string' || Array.isArray(value)
        ? value.length
        : value == null
          ? 0
          : undefined

    if (length === undefined) {
      return false
    }

    const { min, max } = this.options
    if (min !== undefined && length < min) {
      return false
    }
    if (max !== undefined && length > max) {
      return false
    }

    return true
  }

  defaultMessage(ctx: ValidationContext): string {
    return `${ctx.key} must have length between ${this.options.min ?? 0} and ${this.options.max ?? '∞'}`
  }
}

/**
 * Constrangere pentru date, cu limite optionale before/after.
 */
class DateTimeConstraint extends ConstraintAnnotation {
  constructor(private readonly options: { before?: Date; after?: Date }) {
    super()
  }

  check(value: unknown): boolean {
    const date = value instanceof Date ? value : new Date(value as string)
    if (Number.isNaN(date.getTime())) {
      return false
    }

    const { before, after } = this.options
    if (before && date >= before) {
      return false
    }
    if (after && date <= after) {
      return false
    }

    return true
  }

  defaultMessage(ctx: ValidationContext): string {
    return `${ctx.key} must be a valid date within the configured range`
  }
}

/**
 * Constrangere pentru valori numerice in interval.
 */
class RangeConstraint extends ConstraintAnnotation {
  constructor(private readonly options: { min?: number; max?: number }) {
    super()
  }

  check(value: unknown): boolean {
    if (typeof value !== 'number' || Number.isNaN(value)) {
      return false
    }

    const { min, max } = this.options
    if (min !== undefined && value < min) {
      return false
    }
    if (max !== undefined && value > max) {
      return false
    }

    return true
  }

  defaultMessage(ctx: ValidationContext): string {
    return `${ctx.key} must be between ${this.options.min ?? '-∞'} and ${this.options.max ?? '∞'}`
  }
}

/**
 * Constrangere bazata pe expresie regulata.
 */
class PatternConstraint extends ConstraintAnnotation {
  constructor(private readonly regex: RegExp) {
    super()
  }

  check(value: unknown): boolean {
    return typeof value === 'string' && this.regex.test(value)
  }

  defaultMessage(ctx: ValidationContext): string {
    return `${ctx.key} does not match required pattern ${this.regex}`
  }
}

/**
 * Constrangere pentru o lista finita de valori permise.
 */
class EnumConstraint extends ConstraintAnnotation {
  constructor(private readonly values: readonly unknown[]) {
    super()
  }

  check(value: unknown): boolean {
    return this.values.includes(value)
  }

  defaultMessage(ctx: ValidationContext): string {
    return `${ctx.key} must be one of [${this.values.join(', ')}]`
  }
}

/**
 * Colectie de anotari pentru un singur camp.
 * Unicitatea este asigurata pe clasa concreta a anotarii, similar cu Java.
 */
class FieldAnnotations {
  private readonly byClass = new Map<AnnotationConstructor, Annotation>()

  constructor(
    public readonly key: string,
    annotations: Iterable<Annotation> = [],
  ) {
    for (const annotation of annotations) {
      this.add(annotation)
    }
  }

  add(annotation: Annotation): this {
    this.byClass.set(annotation.constructor as AnnotationConstructor, annotation)
    return this
  }

  /** Verifică dacă există o anotare de tipul dat. */
  has(type: AnnotationConstructor): boolean {
    return this.byClass.has(type)
  }

  /** Returnează o anotare de un anumit tip, dacă există. */
  get<T extends Annotation>(type: AnnotationConstructor): T | undefined {
    return this.byClass.get(type) as T | undefined
  }

  toArray(): Annotation[] {
    return Array.from(this.byClass.values())
  }

  toSet(): Set<Annotation> {
    return new Set(this.byClass.values())
  }

  /** Clonează obiectul de anotări (folosit pentru moștenire immutabilă). */
  clone(): FieldAnnotations {
    return new FieldAnnotations(this.key, this.toArray())
  }

  /** Iterează peste anotările stocate pentru acest câmp. */
  [Symbol.iterator](): IterableIterator<Annotation> {
    return this.byClass.values()
  }
}

/**
 * Sursa abstracta de metadata pentru campuri. Consumatorii (validator,
 * transformer, serializer, payload builder) depind de aceasta abstractie
 * in loc de implementarea concreta a registrului (Dependency Inversion).
 */
interface FieldMetadataSource {
  getFor(ctor: ClassCtor): FieldAnnotations[]
}

/**
 * Registru de metadata pentru campuri.
 * Se bazeaza pe un WeakMap de la constructor la harta de campuri.
 */
class FieldMetadataRegistry implements FieldMetadataSource {
  private getParentCtor(target: ClassCtor): ClassCtor | undefined {
    const parent = Object.getPrototypeOf(target) as ClassCtor | null
    return parent && parent !== Function.prototype ? parent : undefined
  }

  /** Obține metadatele moștenite de la clasa părinte. */
  private getInheritedFieldMap(target: ClassCtor): Map<string, FieldAnnotations> {
    const parent = this.getParentCtor(target)
    return parent ? this.getFieldMap(parent) : new Map<string, FieldAnnotations>()
  }

  getFor(ctor: ClassCtor): FieldAnnotations[] {
    return Array.from(this.getFieldMap(ctor).values())
  }

  /** Obține anotările pentru o proprietate specifică a unei clase. */
  getForProperty(ctor: ClassCtor, key: string): FieldAnnotations | undefined {
    return this.getFieldMap(ctor).get(key)
  }

  getFieldMap(ctor: ClassCtor): Map<string, FieldAnnotations> {
    const ownOrInheritedMetadata = getClassMetadata(ctor)
    const metadataFieldMap = getFieldMapFromMetadata(ownOrInheritedMetadata)

    /** Dacă avem metadata direct pe clasă, întoarcem o clonă pentru imutabilitate. */

    if (metadataFieldMap) {
      return cloneFieldMap(metadataFieldMap)
    }

    return this.getInheritedFieldMap(ctor)
  }
}
const registry = new FieldMetadataRegistry()

class MetadataView {
  constructor(private readonly values: Map<string, FieldAnnotations>) {}

  has(key: string): boolean {
    return this.values.has(key)
  }

  get(key: string): FieldAnnotations | undefined {
    return this.values.get(key)
  }
}

/**
 * Registru public pentru utilizare in teste sau in aplicatii externe.
 */
const dtoMetadata = {
  /** Obține o vedere (slice) a metadatelor DTO pentru o clasă. */
  get(target: Constructor): MetadataView | undefined {
    return new MetadataView(registry.getFieldMap(target as ClassCtor))
  },
}

/** Creează un decorator de câmp Stage III și înregistrează anotările pe clasă. */
function createFieldDecorator(
  annotationFactory: () => Annotation | readonly Annotation[],
): DtoFieldDecorator {
  return (_value: undefined, context: ClassFieldDecoratorContext) => {
    if (context.kind !== 'field') {
      return
    }

    if (context.private) {
      throw new Error('DTO field annotations do not support private fields')
    }

    if (typeof context.name !== 'string') {
      throw new Error('DTO field annotations require string property names')
    }

    const fieldMap = getOwnOrCreateFieldMap(context.metadata as DecoratorMetadataObject)
    const fieldAnnotations = fieldMap.get(context.name) ?? new FieldAnnotations(context.name)
    const produced = annotationFactory()
    const annotations = Array.isArray(produced) ? produced : [produced]

    for (const annotation of annotations) {
      fieldAnnotations.add(annotation)
    }

    // Store the field map on the decorator-provided metadata object.
    // Stage III semantics: `context.metadata` is the class-level metadata
    // object (polyfilled via `Symbol.metadata`), so we persist the field map
    // there under the private `DTO_FIELD_ANNOTATIONS` symbol.
    ;(context.metadata as DecoratorMetadataObject)[DTO_FIELD_ANNOTATIONS] =
      context.metadata[DTO_FIELD_ANNOTATIONS] ?? fieldMap

    fieldMap.set(context.name, fieldAnnotations)
  }
}
/**
 * Decorator pentru campuri marcate ca excluse.
 */
// Decorator factory that supports both `@Exclude` and `@Exclude()` usages.
function Exclude(): DtoFieldDecorator
function Exclude(value: undefined, context: ClassFieldDecoratorContext): void
function Exclude(
  ...maybeContext: [] | [undefined, ClassFieldDecoratorContext]
): DtoFieldDecorator | void {
  const factory = () => new ExcludeAnnotation()

  // If used as `@Exclude` (no parens), TS calls the function with
  // (value, context). Detect that and apply decorator directly.
  if (maybeContext.length === 2 && typeof maybeContext[1] === 'object') {
    createFieldDecorator(factory)(maybeContext[0], maybeContext[1])
    return
  }

  // Otherwise return a decorator so `@Exclude()` works.
  return createFieldDecorator(factory)
}

/**
 * Decorator pentru campuri generate automat.
 */
function AutoGeneratedField(): DtoFieldDecorator {
  return createFieldDecorator(() => new AutoGenerated())
}

/**
 * Decorator pentru validatori inline.
 */
function ValidatorField<T = unknown>(fn: ValidatorFn<T>): DtoFieldDecorator {
  return createFieldDecorator(() => new Validator(fn as ValidatorFn<unknown>))
}

/**
 * Decorator pentru transformari inline.
 */
function TransformField<TIn = unknown, TOut = unknown>(
  fn: TransformFn<TIn, TOut>,
): DtoFieldDecorator {
  return createFieldDecorator(() => new Transform(fn as TransformFn<unknown, unknown>))
}

/**
 * Decorator pentru constrangere de marime.
 */
function Size(options: { min?: number; max?: number }): DtoFieldDecorator {
  return createFieldDecorator(() => new SizeConstraint(options))
}

/**
 * Decorator pentru constrangere de data.
 */
function DateTime(options: { before?: Date; after?: Date }): DtoFieldDecorator {
  return createFieldDecorator(() => new DateTimeConstraint(options))
}

/**
 * Decorator pentru constrangere de interval numeric.
 */
function Range(options: { min?: number; max?: number }): DtoFieldDecorator {
  return createFieldDecorator(() => new RangeConstraint(options))
}

/**
 * Decorator pentru constrangere bazata pe regex.
 */
function Pattern(regex: RegExp): DtoFieldDecorator {
  return createFieldDecorator(() => new PatternConstraint(regex))
}

/**
 * Decorator pentru o lista finita de valori permise.
 */
function OneOf(values: readonly unknown[]): DtoFieldDecorator {
  return createFieldDecorator(() => new EnumConstraint(values))
}

/**
 * Decorator ergonomic pentru campuri cu transformari si/sau validatori inline.
 */
function Field(
  options: {
    transform?: TransformFn<unknown, unknown>
    validators?: ValidatorFn<unknown>[]
  } = {},
): DtoFieldDecorator {
  return createFieldDecorator(() => {
    const annotations: Annotation[] = [new FieldDefinition()]

    if (options.transform) {
      annotations.push(new Transform(options.transform))
    }

    if (options.validators) {
      for (const validatorFn of options.validators) {
        annotations.push(new Validator(validatorFn))
      }
    }

    return annotations
  })
}

function resolveCtor(target: Constructor | object): ClassCtor {
  return (typeof target === 'function' ? target : target.constructor) as ClassCtor
}

/** Rezolvă constructorul dintr-un obiect sau dintr-o funcție. */

function getFieldAnnotations(target: Constructor | object): FieldAnnotations[] {
  return registry.getFor(resolveCtor(target))
}

/** Returnează lista de anotări de câmp pentru o clasă/instanță. */

function getFieldAnnotationsFor(
  target: Constructor | object,
  key: string,
): FieldAnnotations | undefined {
  return registry.getForProperty(resolveCtor(target), key)
}

/** Returnează anotările pentru o proprietate specifică a unei clasă/instanță. */

/** Eroare aruncată când validarea DTO eșuează. */
class ParseError extends Error {
  constructor(public readonly issues: Record<string, string>) {
    super('DTO validation failed')
  }
}

/** Transformări și validări pentru instanțe DTO (folosește registrul de metadate). */
class DtoTransformer {
  constructor(private readonly metadata: FieldMetadataSource = registry) {}

  /** Validează o instanță DTO folosind anotările declarate. */
  validate(instance: object): true {
    const ctor = instance.constructor as ClassCtor
    const issues: Record<string, string> = {}

    for (const fieldAnnotations of this.metadata.getFor(ctor)) {
      if (fieldAnnotations.has(AutoGenerated)) {
        continue
      }

      const value = (instance as Record<string, unknown>)[fieldAnnotations.key]
      const ctx: ValidationContext = { key: fieldAnnotations.key, target: instance }

      // Dacă există o transformare care poate arunca, rulăm transformarea
      // în scopul de a captura erorile ca probleme de validare.
      const transformAnnotation = fieldAnnotations.get(Transform) as Transform | undefined
      if (transformAnnotation) {
        try {
          transformAnnotation.fn(value, instance)
        } catch (err) {
          const message = err instanceof Error ? err.message : String(err)
          issues[ctx.key] = message || `${ctx.key} transformation failed`
          continue
        }
      }

      for (const annotation of fieldAnnotations.toArray()) {
        this.collectIssue(annotation, value, ctx, issues)
      }
    }

    if (Object.keys(issues).length > 0) {
      throw new ParseError(issues)
    }

    return true
  }

  private collectIssue(
    annotation: Annotation,
    value: unknown,
    ctx: ValidationContext,
    issues: Record<string, string>,
  ): void {
    if (annotation instanceof Validator) {
      const normalized = this.normalize(annotation.fn(value, ctx), ctx)
      if (!normalized.valid) {
        issues[ctx.key] = normalized.message ?? `${ctx.key} is invalid`
      }
      return
    }

    if (annotation instanceof ConstraintAnnotation) {
      const result = annotation.validate(value, ctx)
      if (!result.valid) {
        issues[ctx.key] = result.message ?? `${ctx.key} is invalid`
      }
    }
  }

  private normalize(result: ValidatorResult, ctx: ValidationContext): ValidationResult {
    if (result == null) {
      return { valid: true }
    }

    if (typeof result === 'boolean') {
      return {
        valid: result,
        message: result ? undefined : `${ctx.key} failed validation`,
      }
    }

    if (typeof result === 'string') {
      return {
        valid: false,
        message: result,
      }
    }

    return result
  }
  transform(instance: object): Record<string, unknown> {
    const ctor = instance.constructor as ClassCtor
    const out: Record<string, unknown> = { ...(instance as Record<string, unknown>) }

    for (const fieldAnnotations of this.metadata.getFor(ctor)) {
      const transformAnnotation = fieldAnnotations.get(Transform) as Transform | undefined
      if (transformAnnotation) {
        out[fieldAnnotations.key] = transformAnnotation.fn(out[fieldAnnotations.key], instance)
      }
    }

    return out
  }
  serialize(instance: object): Record<string, unknown> {
    const ctor = instance.constructor as ClassCtor
    const excludedKeys = new Set(
      this.metadata
        .getFor(ctor)
        .filter((field) => field.has(ExcludeAnnotation))
        .map((field) => field.key),
    )

    const out: Record<string, unknown> = {}
    for (const [key, value] of Object.entries(instance)) {
      if (!excludedKeys.has(key)) {
        out[key] = value
      }
    }

    return out
  }

  build(instance: object): Record<string, unknown> {
    const ctor = instance.constructor as ClassCtor
    const fields = this.metadata.getFor(ctor)
    const skippedKeys = new Set(
      fields
        .filter((field) => field.has(ExcludeAnnotation) || field.has(AutoGenerated))
        .map((field) => field.key),
    )
    const transformsByKey = new Map(
      fields
        .filter((field) => field.has(Transform))
        .map((field) => [field.key, (field.get(Transform) as Transform).fn]),
    )

    const out: Record<string, unknown> = {}
    for (const [key, value] of Object.entries(instance)) {
      if (skippedKeys.has(key)) {
        continue
      }

      out[key] = transformsByKey.has(key) ? transformsByKey.get(key)!(value, instance) : value
    }

    return out
  }
}

const dtoTransformer = new DtoTransformer()

export {
  // Tipuri
  type ValidationContext,
  type ValidationResult,
  type ValidatorResult,
  type ValidatorFn,
  type TransformFn,
  type Constructor,
  type AnnotationConstructor,
  type DtoFieldDecorator,
  // Clase annotation
  Annotation,
  FieldDefinition,
  ExcludeAnnotation,
  AutoGenerated,
  Validator,
  Transform,
  ConstraintAnnotation,
  SizeConstraint,
  DateTimeConstraint,
  RangeConstraint,
  PatternConstraint,
  EnumConstraint,
  FieldAnnotations,
  // Public API
  dtoMetadata,
  // Decorators
  Exclude,
  AutoGeneratedField,
  ValidatorField,
  TransformField,
  Size,
  DateTime,
  Range,
  Pattern,
  OneOf,
  Field,
  // Metadata readers
  getFieldAnnotations,
  getFieldAnnotationsFor,
  // Error class
  ParseError,
  // Exportat pentru alte module, dar nu pentru consumatori finali
  createFieldDecorator,
  dtoTransformer,
}
