// ============================================================================
// field-annotations.ts — sistem de decoratori pentru DTO-uri, bazat pe Stage 3
// ============================================================================
//
// Scop:
//   - fiecare decorator adauga o instanta a unei clase de anotare la un camp;
//   - metadata-ul este stocat intr-un registru orientat pe obiecte, fara a
//     modifica constructorul sau prototype-ul in mod vizibil;
//   - logica de validare, transformare si serializare este delegata catre
//     obiecte specializate, astfel incat OOP sa faca munca grea.
// ============================================================================
/**
 * Clasa de baza pentru toate anotatiile de camp.
 * Fiecare subclasa pastreaza datele specifice si isi poate implementa logica
 * proprie de validare sau transformare.
 */
export class Annotation {
    /** Nume human-readable, implicit numele clasei concrete. */
    get name() {
        return this.constructor.name;
    }
}
/**
 * Anotare structurala simpla care marcheaza un camp ca parte a modelului.
 * Este folosita pentru a asigura ca un camp decorat cu @Field() apare in
 * metadata chiar daca nu are transformari sau validatori.
 */
export class FieldDefinition extends Annotation {
}
/**
 * Marcheaza un camp care trebuie eliminat din payload-ul de iesire.
 */
export class Exclude extends Annotation {
}
/**
 * Marcheaza un camp generat de motorul bazei de date sau de sistem.
 */
export class AutoGenerated extends Annotation {
}
/**
 * Inveleste un validator arbitrar.
 */
export class Validator extends Annotation {
    constructor(fn) {
        super();
        this.fn = fn;
    }
}
/**
 * Inveleste o transformare aplicata la serializare sau creare payload.
 */
export class Transform extends Annotation {
    constructor(fn) {
        super();
        this.fn = fn;
    }
}
/**
 * Clasa de baza pentru anotatiile de constrangere.
 * O constrangere cunoaste propria logica de validare si poate oferi un mesaj
 * implicit personalizat.
 */
export class ConstraintAnnotation extends Annotation {
    validate(value, ctx) {
        if (this.check(value, ctx)) {
            return { valid: true };
        }
        return {
            valid: false,
            message: this.message ?? this.defaultMessage(ctx),
        };
    }
    withMessage(message) {
        this.message = message;
        return this;
    }
}
/**
 * Constrangere pentru lungime sau dimensiune.
 */
export class SizeConstraint extends ConstraintAnnotation {
    constructor(options) {
        super();
        this.options = options;
    }
    check(value) {
        const length = typeof value === 'string' || Array.isArray(value)
            ? value.length
            : value == null
                ? 0
                : undefined;
        if (length === undefined) {
            return false;
        }
        const { min, max } = this.options;
        if (min !== undefined && length < min) {
            return false;
        }
        if (max !== undefined && length > max) {
            return false;
        }
        return true;
    }
    defaultMessage(ctx) {
        return `${ctx.key} must have length between ${this.options.min ?? 0} and ${this.options.max ?? '∞'}`;
    }
}
/**
 * Constrangere pentru date, cu limite optionale before/after.
 */
export class DateTimeConstraint extends ConstraintAnnotation {
    constructor(options) {
        super();
        this.options = options;
    }
    check(value) {
        const date = value instanceof Date ? value : new Date(value);
        if (Number.isNaN(date.getTime())) {
            return false;
        }
        const { before, after } = this.options;
        if (before && date >= before) {
            return false;
        }
        if (after && date <= after) {
            return false;
        }
        return true;
    }
    defaultMessage(ctx) {
        return `${ctx.key} must be a valid date within the configured range`;
    }
}
/**
 * Constrangere pentru valori numerice in interval.
 */
export class RangeConstraint extends ConstraintAnnotation {
    constructor(options) {
        super();
        this.options = options;
    }
    check(value) {
        if (typeof value !== 'number' || Number.isNaN(value)) {
            return false;
        }
        const { min, max } = this.options;
        if (min !== undefined && value < min) {
            return false;
        }
        if (max !== undefined && value > max) {
            return false;
        }
        return true;
    }
    defaultMessage(ctx) {
        return `${ctx.key} must be between ${this.options.min ?? '-∞'} and ${this.options.max ?? '∞'}`;
    }
}
/**
 * Constrangere bazata pe expresie regulata.
 */
export class PatternConstraint extends ConstraintAnnotation {
    constructor(regex) {
        super();
        this.regex = regex;
    }
    check(value) {
        return typeof value === 'string' && this.regex.test(value);
    }
    defaultMessage(ctx) {
        return `${ctx.key} does not match required pattern ${this.regex}`;
    }
}
/**
 * Constrangere pentru o lista finita de valori permise.
 */
export class EnumConstraint extends ConstraintAnnotation {
    constructor(values) {
        super();
        this.values = values;
    }
    check(value) {
        return this.values.includes(value);
    }
    defaultMessage(ctx) {
        return `${ctx.key} must be one of [${this.values.join(', ')}]`;
    }
}
/**
 * Colectie de anotari pentru un singur camp.
 * Unicitatea este asigurata pe clasa concreta a anotarii, similar cu Java.
 */
export class FieldAnnotations {
    constructor(key, annotations = []) {
        this.key = key;
        this.byClass = new Map();
        for (const annotation of annotations) {
            this.add(annotation);
        }
    }
    add(annotation) {
        this.byClass.set(annotation.constructor, annotation);
        return this;
    }
    has(type) {
        return this.byClass.has(type);
    }
    get(type) {
        return this.byClass.get(type);
    }
    toArray() {
        return Array.from(this.byClass.values());
    }
    toSet() {
        return new Set(this.byClass.values());
    }
    clone() {
        return new FieldAnnotations(this.key, this.toArray());
    }
    [Symbol.iterator]() {
        return this.byClass.values();
    }
}
/**
 * Registru de metadata pentru campuri.
 * Se bazeaza pe un WeakMap de la constructor la harta de campuri.
 */
class FieldMetadataRegistry {
    constructor() {
        this.registry = new WeakMap();
    }
    getParentCtor(target) {
        const parent = Object.getPrototypeOf(target);
        return parent && parent !== Function.prototype ? parent : undefined;
    }
    getOrCreateFieldMap(target) {
        const existing = this.registry.get(target);
        if (existing) {
            return existing;
        }
        const parent = this.getParentCtor(target);
        const inherited = parent ? this.getOrCreateFieldMap(parent) : undefined;
        const next = new Map(inherited ? Array.from(inherited.entries(), ([key, value]) => [key, value.clone()]) : []);
        this.registry.set(target, next);
        return next;
    }
    register(instance, key, annotation) {
        const ctor = instance.constructor;
        const fieldMap = this.getOrCreateFieldMap(ctor);
        const fieldAnnotations = fieldMap.get(key) ?? new FieldAnnotations(key);
        fieldAnnotations.add(annotation);
        fieldMap.set(key, fieldAnnotations);
    }
    getFor(ctor) {
        return Array.from(this.getOrCreateFieldMap(ctor).values());
    }
    getForProperty(ctor, key) {
        return this.getOrCreateFieldMap(ctor).get(key);
    }
    getFieldMap(ctor) {
        return this.getOrCreateFieldMap(ctor);
    }
}
const registry = new FieldMetadataRegistry();
class MetadataView {
    constructor(values) {
        this.values = values;
    }
    has(key) {
        return this.values.has(key);
    }
    get(key) {
        return this.values.get(key);
    }
}
/**
 * Registru public pentru utilizare in teste sau in aplicatii externe.
 */
export const dtoMetadata = {
    get(target) {
        return new MetadataView(registry.getFieldMap(target));
    },
};
/**
 * Construiește un decorator de camp bazat pe Stage 3.
 * In loc sa foloseasca target-ul vechi, decoratorul inregistreaza metadata in
 * momentul crearii unei instante, prin intermediul initializer-ului contextului.
 */
function createFieldDecorator(annotationFactory) {
    return (value, context) => {
        const annotation = annotationFactory();
        if (typeof context === 'object' && context !== null && 'kind' in context) {
            if (context.kind !== 'field') {
                return;
            }
            const propertyKey = String(context.name);
            context.addInitializer(function () {
                registry.register(this, propertyKey, annotation);
            });
            return;
        }
        const target = value;
        const propertyKey = String(context);
        registry.register(target, propertyKey, annotation);
    };
}
/**
 * Decorator pentru campuri marcate ca excluse.
 */
export function ExcludeField() {
    return createFieldDecorator(() => new Exclude());
}
/**
 * Decorator pentru campuri generate automat.
 */
export function AutoGeneratedField() {
    return createFieldDecorator(() => new AutoGenerated());
}
/**
 * Decorator pentru validatori inline.
 */
export function ValidatorField(fn) {
    return createFieldDecorator(() => new Validator(fn));
}
/**
 * Decorator pentru transformari inline.
 */
export function TransformField(fn) {
    return createFieldDecorator(() => new Transform(fn));
}
/**
 * Decorator pentru constrangere de marime.
 */
export function Size(options) {
    return createFieldDecorator(() => new SizeConstraint(options));
}
/**
 * Decorator pentru constrangere de data.
 */
export function DateTime(options) {
    return createFieldDecorator(() => new DateTimeConstraint(options));
}
/**
 * Decorator pentru constrangere de interval numeric.
 */
export function Range(options) {
    return createFieldDecorator(() => new RangeConstraint(options));
}
/**
 * Decorator pentru constrangere bazata pe regex.
 */
export function Pattern(regex) {
    return createFieldDecorator(() => new PatternConstraint(regex));
}
/**
 * Decorator pentru o lista finita de valori permise.
 */
export function OneOf(values) {
    return createFieldDecorator(() => new EnumConstraint(values));
}
/**
 * Decorator ergonomic pentru campuri cu transformari si/sau validatori inline.
 */
export function Field(options = {}) {
    return (value, context) => {
        const annotations = [new FieldDefinition()];
        if (options.transform) {
            annotations.push(new Transform(options.transform));
        }
        if (options.validators) {
            for (const validatorFn of options.validators) {
                annotations.push(new Validator(validatorFn));
            }
        }
        if (typeof context === 'object' && context !== null && 'kind' in context) {
            if (context.kind !== 'field') {
                return;
            }
            const propertyKey = String(context.name);
            context.addInitializer(function () {
                for (const annotation of annotations) {
                    registry.register(this, propertyKey, annotation);
                }
            });
            return;
        }
        const target = value;
        const propertyKey = String(context);
        for (const annotation of annotations) {
            registry.register(target, propertyKey, annotation);
        }
    };
}
/**
 * Citeste toate metadata-urile pentru un constructor dat.
 */
export function getFieldAnnotations(target) {
    return registry.getFor(target);
}
/**
 * Citeste metadata pentru un anumit camp.
 */
export function getFieldAnnotationsFor(target, key) {
    return registry.getForProperty(target, key);
}
function normalizeValidatorResult(result, ctx) {
    if (result == null) {
        return { valid: true };
    }
    if (typeof result === 'boolean') {
        return {
            valid: result,
            message: result ? undefined : `${ctx.key} failed validation`,
        };
    }
    if (typeof result === 'string') {
        return {
            valid: false,
            message: result,
        };
    }
    return result;
}
/**
 * Ruleaza validatoarele si constrangerile asociate unei instante DTO.
 * Arunca o eroare agregata atunci cand unul sau mai multe campuri esueaza.
 */
export function validate(instance, options = {}) {
    const ctor = instance.constructor;
    const issues = {};
    for (const fieldAnnotations of getFieldAnnotations(ctor)) {
        if (options.skipAutoGenerated && fieldAnnotations.has(AutoGenerated)) {
            continue;
        }
        const value = instance[fieldAnnotations.key];
        const ctx = { key: fieldAnnotations.key, target: instance };
        for (const annotation of fieldAnnotations.toArray()) {
            if (annotation instanceof Validator) {
                const normalized = normalizeValidatorResult(annotation.fn(value, ctx), ctx);
                if (!normalized.valid) {
                    issues[ctx.key] = normalized.message ?? `${ctx.key} is invalid`;
                }
            }
            else if (annotation instanceof ConstraintAnnotation) {
                const result = annotation.validate(value, ctx);
                if (!result.valid) {
                    issues[ctx.key] = result.message ?? `${ctx.key} is invalid`;
                }
            }
        }
    }
    if (Object.keys(issues).length > 0) {
        throw new ParseError(issues);
    }
    return true;
}
/**
 * Aplica transformarile de camp si returneaza un obiect plain pentru export.
 */
export function transform(instance) {
    const ctor = instance.constructor;
    const out = { ...instance };
    for (const fieldAnnotations of getFieldAnnotations(ctor)) {
        const transformAnnotation = fieldAnnotations.get(Transform);
        if (transformAnnotation) {
            out[fieldAnnotations.key] = transformAnnotation.fn(out[fieldAnnotations.key], instance);
        }
    }
    return out;
}
/**
 * Elimina campurile marcate ca exclude si returneaza un obiect serializabil.
 */
export function serialize(instance) {
    const ctor = instance.constructor;
    const excludedKeys = new Set(getFieldAnnotations(ctor)
        .filter((field) => field.has(Exclude))
        .map((field) => field.key));
    const out = {};
    for (const [key, value] of Object.entries(instance)) {
        if (!excludedKeys.has(key)) {
            out[key] = value;
        }
    }
    return out;
}
/**
 * Elimina campurile generate automat sau excluse si aplica transformarile.
 */
export function toCreatePayload(instance) {
    const ctor = instance.constructor;
    const fields = getFieldAnnotations(ctor);
    const skippedKeys = new Set(fields
        .filter((field) => field.has(Exclude) || field.has(AutoGenerated))
        .map((field) => field.key));
    const transformsByKey = new Map(fields
        .filter((field) => field.has(Transform))
        .map((field) => [field.key, field.get(Transform).fn]));
    const out = {};
    for (const [key, value] of Object.entries(instance)) {
        if (skippedKeys.has(key)) {
            continue;
        }
        out[key] = transformsByKey.has(key) ? transformsByKey.get(key)(value, instance) : value;
    }
    return out;
}
/**
 * Eroare aruncata de AbstractDTOEntity.parse() atunci cand validarea esueaza.
 */
export class ParseError extends Error {
    constructor(issues) {
        super('DTO validation failed');
        this.issues = issues;
    }
}
